# controller
COMMAND_QUEUE_SIZE = 2000
COMMAND_QUEUE_TIMEOUT = 100
COMMAND_QUEUE_FEED_TIMEOUT = 100
COMMAND_QUEUE_CONSUME_DELAY = 10
COMMAND_QUEUE_CONSUME_TIMEOUT = 100

# interface
INTERFACE_PORT = 8888

# motor
PWM_DEFAULT_FREQUENCY = 100
COMPOSITE_DIRECTION_HORIZONTAL_WEIGHT = 1
COMPOSITE_DIRECTION_OPPOSITE_HORIZONTAL_WEIGHT = 0.5
