from flea.utils import directions


# controller
COMMAND_QUEUE_SIZE = 2000
COMMAND_QUEUE_TIMEOUT = 100
COMMAND_QUEUE_FEED_TIMEOUT = 100
COMMAND_QUEUE_CONSUME_DELAY = 10
COMMAND_QUEUE_CONSUME_TIMEOUT = 100

# interface
INTERFACE_PORT = 8888

# motor
PWM_DEFAULT_FREQUENCY = 100
CMP_DIR_HORIZONTAL_WEIGHT = 1
CMP_DIR_HORIZONTAL_OPPOSITE_WEIGHT = 0.5
MOTORS = {
    directions.TL: 16,
    directions.TR: 22,
    directions.BL: 18,
    directions.BR: 24,
}
